### PR TITLE
Kan 10 wishlist code

### PR DESCRIPTION
**Pull request by vivektalpada07**
intoducting search button as per client requirement in products, sloving cart and wishlist problems

### CODE REVIEW

**Review by chathu-123 — COMMENTED** [review]
It looks good

**Review by abhistyalish2802 — APPROVED** [review]
Great job adding the search button as requested by the client. Ensure that all new features are covered by tests to validate their functionality

**Comment by abhistyalish2802** [comment]
Great job on adding the search button and fixing the cart and wishlist issues. A few suggestions from my side is Please add more details about the search functionality and the specific cart and wishlist fixes.
Improve commit messages for clarity. 
Keep it up the good work!

**Review by Hem9025 — APPROVED** [review]
Great that we have also including the search button and it looks great.

**Pull request merged**
